service: duckdb-lambda-layer

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'prd'}

layers:
  duckdb:
    path: release
    compatibleRuntimes:
      - nodejs16.x
      - nodejs18.x
    compatibleArchitectures:
      - x86_64

resources:
  Outputs:
    DuckDBLambdaLayerArn:
        Value:
          Ref: DuckdbLambdaLayer
        Export:
          Name: DuckDBLambdaLayerArn
