name: Build DuckDB Lambda Layer

on:
  push:
    branches: [ main ]

jobs:
  
  deploy:
    name: Upload Layer to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # For more info: https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build
        env:
          release_bucket: dfgdfgdfg
        run: |
          # Cleanup
          rm -rf $PWD/release

          # Create release folder
          mkdir -p $PWD/release

          # Run build
          docker build -t duckdb-lambda .
