name: Build DuckDB Lambda Layer

on:
  push:
    branches: [ main ]

jobs:

  build_geo_extension:
    name: Build and store geo extension
    runs-on: ubuntu-latest

    steps:
      - name: Build geo extension
        run: |
          # Create release folder
          mkdir -p $PWD/release

          # Run build
          docker build -t duckdb-geo-extension -f Dockerfile.geo .

          # Copy release from image
          docker run -v $PWD/release:/opt/mount --rm --entrypoint /bin/bash duckdb-geo-extension -c "cp /tmp/release/geo.duckdb_extension /opt/mount/"

      - name: Upload geo extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: geo-extension
          path: $PWD/release/geo.duckdb_extension
  
  build_prql_extension:
    name: Build and store prql extension
    runs-on: ubuntu-latest

    steps:
      - name: Build prql extension
        run: |
          # Create release folder
          mkdir -p $PWD/release

          # Run build
          docker build -t duckdb-prql-extension -f Dockerfile.prql .

          # Copy release from image
          docker run -v $PWD/release:/opt/mount --rm --entrypoint /bin/bash duckdb-prql-extension -c "cp /tmp/release/prql.duckdb_extension /opt/mount/"

      - name: Upload prql extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: prql-extension
          path: $PWD/release/prql.duckdb_extension
  
  build_layer:
    name: Build and upload DuckDB Lambda layer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1

      - name: Build layer
        run: |
          # Create release folder
          mkdir -p $PWD/release

          # Run build
          docker build -t duckdb-lambda .

          # Copy release from image
          docker run -v $PWD/release:/opt/mount --rm --entrypoint /bin/bash duckdb-lambda -c "cp /tmp/release/duckdb-layer.zip /opt/mount/"          

      - name: Publish layer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: 'true'
        run: bash $PWD/publish_layer.sh
